# Generated by Django 4.2.13 on 2024-05-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0003_alter_email_bcc_alter_email_cc_alter_email_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
