# Generated by Django 4.2.13 on 2024-05-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0004_alter_email_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='preview',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
