# Generated by Django 4.2.13 on 2024-06-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0005_alter_email_preview_alter_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlookaccount',
            name='contact_id',
            field=models.IntegerField(null=True),
        ),
    ]
